CREATE TABLE IF NOT EXISTS supplier_invoice_item_attributions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  invoice_item_id BIGINT UNSIGNED NOT NULL,
  source_loc_code VARCHAR(50) NOT NULL,
  source_mac_code VARCHAR(50) NOT NULL,
  source_txn_date DATE NOT NULL,
  source_receipt_no INT UNSIGNED NOT NULL,
  source_seq_no INT UNSIGNED NOT NULL,
  supplier_id BIGINT UNSIGNED NOT NULL,
  original_supplier_code VARCHAR(120) NOT NULL,
  reason VARCHAR(255) NOT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_supplier_item_attribution_source (invoice_item_id),
  UNIQUE KEY uq_supplier_item_attribution_origin (source_loc_code, source_mac_code, source_txn_date, source_receipt_no, source_seq_no),
  KEY idx_supplier_item_attribution_supplier (supplier_id, invoice_item_id),
  CONSTRAINT fk_supplier_item_attribution_item FOREIGN KEY (invoice_item_id) REFERENCES invoice_items(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_item_attribution_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,
  CONSTRAINT chk_supplier_item_attribution_reason CHECK (CHAR_LENGTH(TRIM(reason)) > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS supplier_invoice_item_attribution_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  attribution_id BIGINT UNSIGNED NOT NULL,
  invoice_item_id BIGINT UNSIGNED NOT NULL,
  source_loc_code VARCHAR(50) NOT NULL,
  source_mac_code VARCHAR(50) NOT NULL,
  source_txn_date DATE NOT NULL,
  source_receipt_no INT UNSIGNED NOT NULL,
  source_seq_no INT UNSIGNED NOT NULL,
  event_no INT UNSIGNED NOT NULL,
  previous_supplier_id BIGINT UNSIGNED NULL,
  assigned_supplier_id BIGINT UNSIGNED NOT NULL,
  original_supplier_code VARCHAR(120) NOT NULL,
  reason VARCHAR(255) NOT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_supplier_attribution_events_source (invoice_item_id, created_at),
  UNIQUE KEY uq_supplier_attribution_events_origin (source_loc_code, source_mac_code, source_txn_date, source_receipt_no, source_seq_no, event_no),
  CONSTRAINT fk_supplier_attribution_events_attribution FOREIGN KEY (attribution_id) REFERENCES supplier_invoice_item_attributions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_attribution_events_item FOREIGN KEY (invoice_item_id) REFERENCES invoice_items(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_attribution_events_supplier FOREIGN KEY (assigned_supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS supplier_sale_statements (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  business_day_id BIGINT UNSIGNED NOT NULL,
  statement_number VARCHAR(160) NOT NULL,
  loc_code VARCHAR(50) NOT NULL,
  mac_code VARCHAR(50) NOT NULL,
  txn_date DATE NOT NULL,
  statement_no INT UNSIGNED NOT NULL,
  replaces_statement_id BIGINT UNSIGNED NULL,
  supplier_id BIGINT UNSIGNED NOT NULL,
  from_date DATE NOT NULL,
  to_date DATE NOT NULL,
  status ENUM('draft','reviewed','finalized','void') NOT NULL DEFAULT 'draft',
  build_mode ENUM('assisted','manual','hybrid') NOT NULL DEFAULT 'assisted',
  commission_rate DECIMAL(7,4) NOT NULL DEFAULT 0,
  commission_rounding ENUM('cents','nearest_rupee','floor_rupee','ceil_rupee','manual') NOT NULL DEFAULT 'cents',
  commission_override DECIMAL(12,2) NULL,
  commission_override_reason VARCHAR(255) NULL,
  gross_merchandise_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  refund_merchandise_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  merchandise_subtotal DECIMAL(14,2) NOT NULL DEFAULT 0,
  bag_charge_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  wage_charge_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  commission_base DECIMAL(14,2) NOT NULL DEFAULT 0,
  commission_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  adjustment_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  net_payable DECIMAL(14,2) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  financial_posting_status ENUM('evaluation_only','posted','reversed') NOT NULL DEFAULT 'evaluation_only',
  created_by BIGINT UNSIGNED NULL,
  reviewed_by BIGINT UNSIGNED NULL,
  finalized_by BIGINT UNSIGNED NULL,
  voided_by BIGINT UNSIGNED NULL,
  void_reason VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  reviewed_at TIMESTAMP NULL,
  finalized_at TIMESTAMP NULL,
  voided_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_supplier_sale_statements_number (statement_number),
  UNIQUE KEY uq_supplier_sale_statements_origin (loc_code, mac_code, txn_date, statement_no),
  KEY idx_supplier_sale_statements_register (supplier_id, status, txn_date, id),
  KEY idx_supplier_sale_statements_period (supplier_id, from_date, to_date),
  KEY idx_supplier_sale_statements_business_day (business_day_id, status),
  CONSTRAINT fk_supplier_sale_statements_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_sale_statements_replaces FOREIGN KEY (replaces_statement_id) REFERENCES supplier_sale_statements(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_sale_statements_business_day_identity
    FOREIGN KEY (business_day_id, loc_code, txn_date)
    REFERENCES business_days (id, loc_code, business_date) ON DELETE RESTRICT,
  CONSTRAINT chk_supplier_sale_statements_origin CHECK (CHAR_LENGTH(TRIM(loc_code)) > 0 AND CHAR_LENGTH(TRIM(mac_code)) > 0 AND statement_no > 0),
  CONSTRAINT chk_supplier_sale_statements_period CHECK (from_date <= to_date),
  CONSTRAINT chk_supplier_sale_statements_commission CHECK (commission_rate >= 0 AND commission_rate <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS supplier_sale_statement_grns (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  statement_id BIGINT UNSIGNED NOT NULL,
  loc_code VARCHAR(50) NOT NULL,
  mac_code VARCHAR(50) NOT NULL,
  txn_date DATE NOT NULL,
  statement_no INT UNSIGNED NOT NULL,
  line_no INT UNSIGNED NOT NULL,
  goods_receipt_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_supplier_sale_statement_grn (statement_id, goods_receipt_id),
  UNIQUE KEY uq_supplier_sale_statement_grn_origin (loc_code, mac_code, txn_date, statement_no, line_no),
  KEY idx_supplier_sale_statement_grns_receipt (goods_receipt_id),
  CONSTRAINT fk_supplier_sale_statement_grns_statement FOREIGN KEY (statement_id) REFERENCES supplier_sale_statements(id) ON DELETE CASCADE,
  CONSTRAINT fk_supplier_sale_statement_grns_receipt FOREIGN KEY (goods_receipt_id) REFERENCES goods_receipts(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS supplier_sale_statement_allocations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  statement_id BIGINT UNSIGNED NOT NULL,
  loc_code VARCHAR(50) NOT NULL,
  mac_code VARCHAR(50) NOT NULL,
  txn_date DATE NOT NULL,
  statement_no INT UNSIGNED NOT NULL,
  line_no INT UNSIGNED NOT NULL,
  invoice_item_id BIGINT UNSIGNED NOT NULL,
  source_invoice_id BIGINT UNSIGNED NOT NULL,
  source_loc_code VARCHAR(50) NOT NULL,
  source_mac_code VARCHAR(50) NOT NULL,
  source_txn_date DATE NOT NULL,
  source_receipt_no INT UNSIGNED NOT NULL,
  source_seq_no INT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NULL,
  source_supplier_code VARCHAR(120) NOT NULL,
  attributed_supplier_id BIGINT UNSIGNED NOT NULL,
  attribution_mode ENUM('source','corrected','cross_supplier') NOT NULL DEFAULT 'source',
  attribution_reason VARCHAR(255) NULL,
  item_code VARCHAR(120) NOT NULL,
  description VARCHAR(255) NOT NULL,
  pricing_basis ENUM('qty','kilos') NOT NULL DEFAULT 'qty',
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  allocated_quantity DECIMAL(14,3) NOT NULL DEFAULT 0,
  allocated_kilos DECIMAL(14,3) NULL,
  gross_merchandise_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  refund_merchandise_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  merchandise_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  bag_charge_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  wage_charge_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  note VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_supplier_sale_statement_source (statement_id, invoice_item_id),
  UNIQUE KEY uq_supplier_sale_statement_allocation_line (statement_id, line_no),
  UNIQUE KEY uq_supplier_sale_statement_allocation_origin (loc_code, mac_code, txn_date, statement_no, line_no),
  KEY idx_supplier_sale_statement_alloc_source (invoice_item_id, statement_id),
  KEY idx_supplier_sale_statement_alloc_group (statement_id, product_id, pricing_basis, unit_price),
  CONSTRAINT fk_supplier_sale_statement_alloc_statement FOREIGN KEY (statement_id) REFERENCES supplier_sale_statements(id) ON DELETE CASCADE,
  CONSTRAINT fk_supplier_sale_statement_alloc_item FOREIGN KEY (invoice_item_id) REFERENCES invoice_items(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_sale_statement_alloc_invoice FOREIGN KEY (source_invoice_id) REFERENCES invoices(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_sale_statement_alloc_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
  CONSTRAINT fk_supplier_sale_statement_alloc_supplier FOREIGN KEY (attributed_supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,
  CONSTRAINT chk_supplier_sale_statement_alloc_line CHECK (line_no > 0),
  CONSTRAINT chk_supplier_sale_statement_alloc_values CHECK (allocated_quantity >= 0 AND (allocated_kilos IS NULL OR allocated_kilos >= 0) AND merchandise_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS supplier_sale_statement_manual_lines (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  statement_id BIGINT UNSIGNED NOT NULL,
  loc_code VARCHAR(50) NOT NULL,
  mac_code VARCHAR(50) NOT NULL,
  txn_date DATE NOT NULL,
  statement_no INT UNSIGNED NOT NULL,
  line_no INT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NULL,
  item_code VARCHAR(120) NOT NULL,
  description VARCHAR(255) NOT NULL,
  pricing_basis ENUM('qty','kilos') NOT NULL DEFAULT 'kilos',
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  quantity DECIMAL(14,3) NOT NULL DEFAULT 0,
  kilos DECIMAL(14,3) NULL,
  merchandise_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  reason VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_supplier_sale_statement_manual_line (statement_id, line_no),
  UNIQUE KEY uq_supplier_sale_statement_manual_origin (loc_code, mac_code, txn_date, statement_no, line_no),
  KEY idx_supplier_sale_statement_manual_group (statement_id, product_id, pricing_basis, unit_price),
  CONSTRAINT fk_supplier_sale_statement_manual_statement FOREIGN KEY (statement_id) REFERENCES supplier_sale_statements(id) ON DELETE CASCADE,
  CONSTRAINT fk_supplier_sale_statement_manual_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
  CONSTRAINT chk_supplier_sale_statement_manual_values CHECK (line_no > 0 AND quantity >= 0 AND (kilos IS NULL OR kilos >= 0) AND merchandise_amount >= 0),
  CONSTRAINT chk_supplier_sale_statement_manual_reason CHECK (CHAR_LENGTH(TRIM(reason)) > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS supplier_sale_statement_adjustments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  statement_id BIGINT UNSIGNED NOT NULL,
  loc_code VARCHAR(50) NOT NULL,
  mac_code VARCHAR(50) NOT NULL,
  txn_date DATE NOT NULL,
  statement_no INT UNSIGNED NOT NULL,
  line_no INT UNSIGNED NOT NULL,
  adjustment_type ENUM('deduction','credit') NOT NULL,
  label VARCHAR(120) NOT NULL,
  amount DECIMAL(14,2) NOT NULL,
  note VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_supplier_sale_statement_adjustment_line (statement_id, line_no),
  UNIQUE KEY uq_supplier_sale_statement_adjustment_origin (loc_code, mac_code, txn_date, statement_no, line_no),
  CONSTRAINT fk_supplier_sale_statement_adjustment_statement FOREIGN KEY (statement_id) REFERENCES supplier_sale_statements(id) ON DELETE CASCADE,
  CONSTRAINT chk_supplier_sale_statement_adjustment CHECK (line_no > 0 AND amount > 0 AND CHAR_LENGTH(TRIM(label)) > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS supplier_sale_statement_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  statement_id BIGINT UNSIGNED NOT NULL,
  loc_code VARCHAR(50) NOT NULL,
  mac_code VARCHAR(50) NOT NULL,
  txn_date DATE NOT NULL,
  statement_no INT UNSIGNED NOT NULL,
  event_no INT UNSIGNED NOT NULL,
  event_type ENUM('created','saved','reviewed','reopened','finalized','voided') NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  reason VARCHAR(255) NULL,
  details JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_supplier_sale_statement_event (statement_id, event_no),
  UNIQUE KEY uq_supplier_sale_statement_event_origin (loc_code, mac_code, txn_date, statement_no, event_no),
  CONSTRAINT fk_supplier_sale_statement_event_statement FOREIGN KEY (statement_id) REFERENCES supplier_sale_statements(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
