const corePermissions = [
  { key: 'billing.view', name: 'Billing View' },
  { key: 'billing.create', name: 'Billing Create' },
  { key: 'refund.view', name: 'Refund View' },
  { key: 'refund.create', name: 'Refund Create' },
  { key: 'cash.shift.view', name: 'Cash Shift View' },
  { key: 'cash.shift.open', name: 'Cash Shift Open' },
  { key: 'cash.movement.create', name: 'Cash Movement Create' },
  { key: 'cash.count.create', name: 'Cash Count Create' },
  { key: 'cash.shift.blindClose', name: 'Cash Shift Blind Close' },
  { key: 'cash.shift.close', name: 'Cash Shift Close' },
  { key: 'business-day.view', name: 'Business Day View' },
  { key: 'business-day.open', name: 'Business Day Open' },
  { key: 'business-day.close', name: 'Business Day Close' },
  { key: 'business-day.reopen', name: 'Business Day Reopen' },
  { key: 'products.manage', name: 'Products Manage' },
  { key: 'suppliers.view', name: 'Suppliers View' },
  { key: 'suppliers.manage', name: 'Suppliers Manage' },
  { key: 'receiving.view', name: 'Receiving View' },
  { key: 'receiving.manage', name: 'Receiving Manage' },
  { key: 'inventory.adjust', name: 'Inventory Adjust' },
  { key: 'supplier-settlements.view', name: 'Supplier Settlements View' },
  { key: 'supplier-settlements.manage', name: 'Supplier Settlements Manage' },
  { key: 'reports.export', name: 'Reports Export' },
  { key: 'customers.view', name: 'Customers View' },
  { key: 'customers.manage', name: 'Customers Manage' },
  { key: 'receivables.view', name: 'Receivables View' },
  { key: 'receivables.collect', name: 'Receivables Collect' },
  { key: 'customer-advances.view', name: 'Customer Advances View' },
  { key: 'customer-advances.create', name: 'Customer Advances Create' },
  { key: 'customer-advances.refund', name: 'Customer Advances Refund' },
  { key: 'cheques.view', name: 'Cheque Registers View' },
  { key: 'cheques.manage', name: 'Cheque Registers Manage' },
  { key: 'reports.view', name: 'Reports View' },
  { key: 'field-inbox.view', name: 'Field Transaction Inbox View' },
  { key: 'field-inbox.resolve', name: 'Field Transaction Inbox Resolve' },
  { key: 'settings.manage', name: 'Settings Manage' },
  { key: 'users.manage', name: 'Users Manage' },
];

module.exports = { corePermissions };
